.tekton/acs-konflux-tasks-push.yaml
tasks/determine-image-tag-stackrox-task.yaml
tasks/determine-image-tag-task.yaml
tasks/fetch-external-networks-task.yaml
tasks/fetch-scanner-v2-data-task.yaml
tasks/fetch-scanner-v4-vuln-mappings-task.yaml
tasks/retag-image-task.yaml

`update-tasks-trust` failed in master push of https://github.com/stackrox/konflux-tasks/pull/3 (see https://github.com/stackrox/konflux-tasks/commit/5c84623d4d66726551c3ef71357924d131315ea3 / https://github.com/stackrox/konflux-tasks/runs/34534649551).
```
time="2024-12-17T13:16:36Z" level=debug msg="globalTimeout is 300000000000" func=func1 file=" root_cmd.go:80"
Error: GET https://quay.io/v2/rhacs-eng/konflux-tasks-trust/manifests/latest: MANIFEST_UNKNOWN: manifest unknown; map[]
```
That's because it was the first attempt to push to `latest` tag which did not exist yet.
The same did not happen in my PR https://github.com/stackrox/konflux-tasks/pull/3 because when experimenting with `ec track bundle` I first used `--output` argument and got `pr-3` tag allocated this way.
This change …

ROX-27350: Fix `update-tasks-trust`

---

.tekton/acs-konflux-tasks-push.yaml

The one tends to fail at times. See https://redhat-internal.slack.com/archives/C05TS9N0S7L/p1734527494625329

build: Add retries to `build-container` task

---

.github/renovate.json5

I suggest reviewing this change by commits, I broke down changes and assisted them with commit messages.
Ran config validator, it was ok.

ROX-27352: Setup Renovate config for our tasks

---

tasks/fetch-scanner-v2-data-task.yaml

This is a follow-up from <https://github.com/stackrox/stackrox/pull/13577#discussion_r1891717175>.
I suggest reviewing this per commit.
Via CI in <https://github.com/stackrox/scanner/pull/1751> where builds successfully pass the `fetch-scanner-data` task.

ROX-27480: Inline `fetch-scanner-data.sh`

---

README.md

So that the information is on the surface without the need to dig into the pipeline code.
Readme preview: https://github.com/stackrox/konflux-tasks/blob/misha/mention-quay-repos-in-readme/README.md

doc: Mention Quay repos in top-level readme

---

.github/renovate.json5
.tekton/acs-konflux-tasks-push.yaml

After I first set up Renovate config in https://github.com/stackrox/konflux-tasks/pull/11, renovate automerging did not start happening which I saw in https://github.com/stackrox/konflux-tasks/pull/4 and https://github.com/stackrox/konflux-tasks/pull/17 after those PRs got rebased.
The root cause is that we require an approval from CODEOWNERS in order to merge a PR. Apparently, there's no way Renovate can bypass that.
See <https://docs.renovatebot.com/key-concepts/automerge/#codeowners>:
> Depending on the platform, having a `CODEOWNERS` file could block automerging, because it means a code owner must review the PR.
In my searches of GitHub issues, I did not find a way around it.
Also, https://github.com/apps/renovate-approve says it's not usable for this problem:
> Important note: Due to …

ROX-27352: Try enable Renovate automerge

---

.tekton/acs-konflux-tasks-push.yaml

It's not `master`, it is `main`.
Made a mistake in https://github.com/stackrox/konflux-tasks/pull/18 and then saw on-merge CI was not happening.

ROX-27352: Fix "master" branch name in CEL expression

---

.github/renovate.json5

Renovate automerging started happening after https://github.com/stackrox/konflux-tasks/pull/18.
I thought we need to additionally configure StackRox, Collector and Scanner repos to update our `quay.io/rhacs-eng/konflux-tasks` image but this seems to be happening without any extra config. Yay!
See https://github.com/stackrox/stackrox/pull/13493 and https://github.com/stackrox/collector/pull/2003.
What remains in the scope of https://issues.redhat.com/browse/ROX-27352 is to calm down Renovate to not send changes during our working hours.
In this change I simply restore the same `after 3am and before 7am` expression we use in other repos. I don't know yet whether it would be too frequent or ok.
Note that this schedule configures the time when Renovate will create new branches or refresh …

ROX-27352: Set automerge schedule to create branches at quiet time

---

.tekton/acs-konflux-tasks-push.yaml

In https://console.redhat.com/application-pipeline/workspaces/rh-acs/applications/acs-konflux-tasks/pipelineruns/acs-konflux-tasks-on-push-tzqlj I noticed `apply-tags` fails with:
> `step-apply-additional-tags-from-parameter
Applying tag konflux/mintmaker/all
time="2025-01-13T11:41:44Z" level=fatal msg="Invalid destination name docker://quay.io/rhacs-eng/konflux-tasks:konflux/mintmaker/all: invalid reference format"`
That was not a PR-triggered pipeline, but a push-triggered to `konflux/mintmaker/all` branch. I.e. renovate on-push CI.
The tag is invalid because `/` characters aren't allowed there.
I this PR I convert all non-accepted characters to dashes. The allowed characters are mentioned in https://docs.docker.com/reference/cli/docker/image/tag/
I don't put a length limit because …

build: Fix image tag for renovate branches

---

tasks/determine-image-tag-task.yaml

Per description.
This isn't needed for Stable Stream, only for Fast Stream but I thought it's easier to do now when the context is fresh for me than to come back to this later.
For reviewer(s): please see my comment (below) and share your preferences.
- https://github.com/stackrox/stackrox/pull/13995
- https://github.com/stackrox/scanner/pull/1788
- https://github.com/stackrox/collector/pull/2021

ROX-22250: Sanitize tags: `<N>.<M>.x` to `<N>.<M>.0`

---

tasks/determine-dependency-image-tag-task.yaml
tasks/determine-image-tag-task.yaml
tasks/fetch-external-networks-task.yaml
tasks/fetch-scanner-v2-data-task.yaml
tasks/fetch-scanner-v4-vuln-mappings-task.yaml

There's an ongoing problem around trusted artifacts step failures https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1738140793949009
When looking at one such failing pod, I noticed
```
Limits:
memory:  2Gi
Requests:
cpu:     50m
memory:  128Mi
```
I suspect the failures may be related to memory pressure on the nodes, it will help to set requests same as limits. It also makes it simpler to reason about oom kills when requests are the same as limits because we know that kills happen at the predictable boundary.
As a precedent, we had to bump resources in Collector builds before. https://github.com/stackrox/collector/pull/1913
This will not help with failures in tasks we don't own. For that we can only create overrides how it's done in Collector …

chore: Set fixed memory requests==limits for TA tasks

---

tasks/determine-image-expiration-parameter-task.yaml
tasks/determine-image-expiration-task.yaml

Validated with https://github.com/stackrox/scanner/pull/1806
- PR with target branch master: 
- https://github.com/stackrox/scanner/pull/1806/commits/1326d3cf8d6814a63203cc20c98b0f1aa372884d
- https://console.redhat.com/application-pipeline/workspaces/rh-acs/applications/acs/pipelineruns/scanner-slim-on-push-l7fk8
- https://console.redhat.com/application-pipeline/workspaces/rh-acs/applications/acs/taskruns/scanner-slim-on-push-l7fk8-determine-image-expiration/details --> result is set to 13w.
- `podman inspect quay.io/rhacs-eng/scanner-slim:2.35.x-69-g1326d3cf8d-fast | jq -r '.[].Config.Labels["quay.expires-after"]` -> `13w`
- Pushing a tag:
- https://github.com/stackrox/scanner/tree/0.0.0-tm-test.1
- https://console.redhat.com/application-pipeline/workspaces/rh-acs/applications/acs/pipeli …

ROX-27831: set image expiration based on event type and target branch

---

.github/renovate.json5

I noticed that Renovate branches ([konflux/mintmaker/all](https://github.com/stackrox/konflux-tasks/commits/konflux/mintmaker/all) and [konflux/references/main](https://github.com/stackrox/konflux-tasks/commits/konflux/references/main)) can sit there with changes for multiple hours and days without getting merged.
Here I suggest slight tweaks to try and see if Renovate will become more active.
As compared to <https://github.com/stackrox/konflux-tasks/pull/36>:
- I suggest to keep `schedule` because I saw how in other repos Renovate could open a PR right after I merged one and that was annoying. Keeping the current `schedule` we have at most one change initiated per day.
- I keep the `branch` automerge strategy, i.e. without PRs (until/unless there are CI failures) and without …

ROX-27901: Tweak Renovate's branch automerge schedule

---

tasks/post-bigquery-metrics-task.yaml

This follows up on https://github.com/stackrox/konflux-tasks/pull/41.
The moment I tried adding the task to the StackRox repo, it [failed](https://github.com/stackrox/stackrox/pull/14798/checks?check_run_id=39578621898) saying
> stackroxci:bqjob_r10d5eb469e0c999a_00000195dc572b29_1': Resources exceeded during query execution: Too many DML statements outstanding against table acs-san-stackroxci:ci_metrics.stackrox_jobs, limit is 20. at [21:3]
While I can't queue executions from different pipelines, I can at least add retries.
See related https://redhat-internal.slack.com/archives/C0321S70YK1/p1743159666168609?thread_ts=1731937635.189999&cid=C0321S70YK1
Also, there's likely a pipeline name uniqueness problem and this PR addressed that. Ref …

ROX-27856: Improve BigQuery metrics task

---

tasks/post-bigquery-metrics-task.yaml

BigQuery being analytical data store does not support primary keys or traditional indexes (the ones supported are for full text search and some vector approximation, see [here](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language)). Therefore, the update or upsert operations have to scan the entire table in order to identify required rows.
This would be no issue if we'd update/upsert in bulk and rarely but we do that by 1 record at a time. This means, every time the operation is `O(N)` where `N` is the amount of records in the table.
I suggest we change the approach for Konflux records and insert 1 record when the pipeline starts and 1 record when the pipeline ends. This may require changes to queries/dashboards that calculate the pipeline duration (we'd …

ROX-27856: Insert two rows instead of insert+update

---

.github/renovate.json5

In spite of repeated requests to stop explicitly depending on `"github>konflux-ci/mintmaker//config/renovate/renovate.json"`, I want to give it a try in this repo because we have evidence of MintMaker working ok and automerging.
- https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1742302893466149?thread_ts=1742299353.416699&cid=C04PZ7H0VA8
- https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1745492139282819?thread_ts=1745309786.090319&cid=C04PZ7H0VA8
Only ran CLI for linting.
I don't know how the thing will be running but I'll observe this repo after merging.

ROX-27901: Stop explicitly inheriting Konflux config

---

tasks/determine-image-tag-task.yaml

Per title and ticket.
Paired with https://github.com/stackrox/stackrox/pull/15309
The PR can be reviewed by commits.
- Default (unchanged) behavior in https://github.com/stackrox/stackrox/pull/15309
- PR with a special branch in https://github.com/stackrox/stackrox/pull/15351
- `release-x.y` branch with the holdfile still in place. https://github.com/stackrox/stackrox/commit/de7008cd0cedf37716985db8c28f12f0a13c6693
- `release-x.y` branch without the holdfile. https://github.com/stackrox/stackrox/commit/4edaeb73a3e71a6ad2d652715a9f349b04e0050b
- I did not validate how it works with PRs targeting release branch, nor with tag pushes. I hope that's going to just work, or we'll find it out.
The basic behavior is expected: the suppression happens when I programmed it and does not happen when I …

ROX-27716: Add support for image tag suffix suppression

---

.tekton/acs-konflux-tasks-push.yaml

So that images don't get GC-ed by quay.io when all floating tags move somewhere else.
- Checked that the tasks image gets tagged:
```bash
$ oras discover quay.io/rhacs-eng/konflux-tasks:rev-1f4b6497de7ae6f642cbded470a485adb7032f05
quay.io/rhacs-eng/konflux-tasks@sha256:43074c901e25f348c6eac472708563327a496621dfaddc33562e5a39a21850b2
└── application/sarif+json
└── sha256:47aabffacf436528ecdfca8e84ab0f0f1f0b695ebe3997b53cae855e54a180c0
$ oras discover quay.io/rhacs-eng/konflux-tasks:pr-57
quay.io/rhacs-eng/konflux-tasks@sha256:43074c901e25f348c6eac472708563327a496621dfaddc33562e5a39a21850b2
└── application/sarif+json
└── sha256:47aabffacf436528ecdfca8e84ab0f0f1f0b695ebe3997b53cae855e54a180c0
$ oras discover quay.io/rhacs-eng/konflux-tasks:rev-1f4b6497de7ae6f642cbded470a485adb7032f05-should-p …
```

ROX-29410: Apply a unique tag to the images on build

---

tasks/determine-image-expiration-task.yaml
tasks/determine-image-tag-task.yaml

* https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/rh-acs-tenant/applications/acs/pipelineruns/central-db-on-push-9gk22
* https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/rh-acs-tenant/applications/acs/pipelineruns/central-db-on-push-6l8p9, triggered by https://github.com/stackrox/stackrox/commit/3a11acbaf91a9f33e0ab117a54cc1eeb19c571aa#commitcomment-158023352
* https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/rh-acs-tenant/applications/acs/pipelineruns/central-db-on-push-mzvt8 (added tag after previous experiment "retest of branch build" succeeded)
* https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/rh-acs-tenant/applications/acs/pipelineruns/central-db-on-push-4jjx7, triggered by …

ROX-28973: retest-comment uses git tag if available

---

.tekton/acs-konflux-tasks-push.yaml
tasks/determine-image-expiration-task.yaml
tasks/determine-image-tag-task.yaml

* For normal PR: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/rh-acs-tenant/applications/acs-konflux-tasks/pipelineruns/acs-konflux-tasks-on-push-bcf6w
* For retested PR: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/rh-acs-tenant/applications/acs-konflux-tasks/pipelineruns/acs-konflux-tasks-on-push-4stkx
* Branch build: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/rh-acs-tenant/applications/acs-konflux-tasks/pipelineruns/acs-konflux-tasks-on-push-25j6j
* Retested branch build: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/rh-acs-tenant/applications/acs-konflux-tasks/pipelineruns/acs-konflux-tasks-on-push-bpcbf

ROX-29484: allow retests for branch PipelineRuns

---

.tekton/acs-konflux-tasks-push.yaml

See https://redhat-internal.slack.com/archives/C05TS9N0S7L/p1749037676916069
In https://github.com/stackrox/konflux-tasks/commit/e28dd60112200587e0c55bf6ef384f5aa283443e / <https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/rh-acs-tenant/applications/acs-konflux-tasks/pipelineruns/acs-konflux-tasks-on-push-427hc>. `get-floating-tag` produced `misha-test-for-ROX-29484` despite `pipelinesascode.tekton.dev/source-branch=refs/heads/misha/test-for-ROX-29484`.

ROX-29484: Strip `refs/heads/` from the beginning of both branches

---

tasks/determine-image-tag-task.yaml

Per ticket.
Via https://github.com/stackrox/stackrox/pull/15985 and https://github.com/stackrox/scanner/pull/1967.
In StackRox (not tagged) logs look like this (bash/go warning omitted):
```
>>> Target branch as reported by Tekton: 'master'
>>> Tag from Tekton: ''
>>> Tekton event: pull_request
>>> Tag reported by Makefile: '4.9.x-221-g7877f16eab'
>>> Tags seen by git: ''
>>> Long git describe output: '4.9.x-221-g7877f16eab'
>>> Using Makefile output '4.9.x-221-g7877f16eab' for the tag.
>>> This is StackRox repo, using '.x'->'.0' sanitized tag '4.9.0-221-g7877f16eab'.
>>> Konflux TARGET_BRANCH: master
>>> Konflux SOURCE_BRANCH: misha/ROX-30075-test-new-konflux-tags
>>> Did not spot the magic string in the SOURCE_BRANCH.
>>> This does not look like a release branch or release tag push, nor …
```

ROX-30075: Sanitize `.x` in git tags

---

tasks/post-bigquery-metrics-task.yaml

Since bigquery insert is not critical maybe we can run it async and in batch mode.
See:
- https://github.com/stackrox/stackrox/pull/16052#discussion_r2211175747

perf: nosync and batch biqguery

---

tasks/determine-image-expiration-task.yaml

Running the stage release pipeline reveals a new failure in Conforma.
```
✕ [Violation] quay_expiration.expires_label
ImageRef: quay.io/rhacs-eng/release-scanner-v4-db@sha256:874194eb1765ccb7afbadc371ac2fc4c8eac406a5e974017d6030b18eba9f029
Reason: The label 'quay.expires-after' is not allowed in the released image
Title: Expires label
Description: Check the image metadata for the presence of a "quay.expires-after" label. If it's present then produce a
violation. This check is enforced only for a "release", "production", or "staging" pipeline, as determined by the value of the
`pipeline_intention` rule data. To exclude this rule add "quay_expiration.expires_label" to the `exclude` section of the policy
configuration.
Solution: Make sure the image is built without setting the …
```

ROX-29969: Update image expiration check to follow our release-like definition
